### ISSUE TITLE
how to deploy this to streamlit?

### ISSUE THREAD

**Issue by marioseixas** [borh/TopicModelingStreamlit#1]
i'm a newbie, how can I use this?

**Comment by marioseixas** [comment]
i managed, thanks

**Comment by borh** [comment]
Thanks for trying this out. The Python dependencies are managed using Poetry, and native/rest with [Devenv](https://devenv.sh/). This is a demo that lets you run Gensim and BERTopic on two pre-selected corpora (Japanese and English novels), with currently no way to use your own corpus.

Note that I may move from Streamlit to some other system going forward. I used this in one of my classes and some of the limitations of Streamlit made it hard to proceed from the current state. I have more work scheduled before October, but if I move from Streamlit I will deprecate the project and link to the new one.
